name: example
description: An example of using dartantic_ai.
publish_to: none

environment:
  sdk: ^3.7.2

dependencies:
  dartantic_ai:
    path: ..
  dotprompt_dart: ^0.2.0
  google_generative_ai: ^0.4.7
  http: ^1.2.0
  json_annotation: ^4.9.0
  openai_dart: ^0.4.5
  soti_schema: ^1.0.0
  timezone: ^0.10.1

dev_dependencies:
  all_lint_rules_community: ^0.0.43
  build_runner: ^2.4.15
  json_serializable: ^6.9.0