name: dartantic_ai
description: A Dart library for easily interacting with LLMs in a typed manner.
version: 0.6.0
repository: https://github.com/csells/dartantic_ai

environment:
  sdk: ^3.7.2

dependencies:
  dotprompt_dart: ^0.2.0
  google_generative_ai: ^0.4.7
  json_schema: ^5.2.1
  logging: ^1.3.0
  mcp_dart: ^0.5.1
  openai_dart: ^0.4.5
  uuid: ^4.3.3

dev_dependencies:
  all_lint_rules_community: ^0.0.43
  build_runner: ^2.5.0
  pubspec_extract: ^2.0.8
  test: ^1.24.0
