name: dartantic_ai
description: >
  Dartantic is an agentic framework designed to make building client and
  server-side apps in Dart with generative AI easier and more fun!
version: 1.0.1
repository: https://github.com/csells/dartantic_ai

environment:
  sdk: ^3.8.1

dependencies:
  anthropic_sdk_dart: ^0.2.1
  collection: ^1.19.1
  dartantic_interface: ^1.0.1
  google_generative_ai: ^0.4.7
  html: ^0.15.6
  http: ^1.4.0
  json_schema: ^5.1.8
  logging: ^1.3.0
  mcp_dart: ^0.5.3
  meta: ^1.16.0
  mistralai_dart: ^0.0.4
  ollama_dart: ^0.2.3
  openai_dart: ^0.5.2
  rxdart: ^0.28.0
  uuid: ^4.2.2

dev_dependencies:
  all_lint_rules_community: ^0.0.43
  exception_hiding_lint:
    path: ../../../exception_hiding_lint
  test: ^1.24.0
