name: chatarang
description: A chat agent that uses Dartantic.
version: 0.1.0
publish_to: none

environment:
  sdk: ^3.8.1

dependencies:
  all_lint_rules_community: ^0.0.43
  cli_repl: ^0.2.3
  dartantic_ai:
    path: ../../packages/dartantic_ai
  dartantic_interface: ^1.0.1
  http: ^1.4.0
  json_schema: ^5.2.1

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
