name: dartantic_interface
description: Interface definitions for dartantic_ai for use in building custom providers.
version: 1.0.1
repository: https://github.com/csells/dartantic_ai

environment:
  sdk: ^3.8.1

dependencies:
  cross_file: ^0.3.4+2
  json_schema: ^5.2.1
  logging: ^1.3.0
  meta: ^1.16.0
  mime: ^2.0.0
  path: ^1.9.1
  uuid: ^4.5.1

dev_dependencies:
  all_lint_rules_community: ^0.0.43
